export const ADDITION = 'ADDITION';
export const SUBTRACTION = 'SUBTRACTION';
export const SETINITIALLOGIN = 'SETINITIALLOGIN';
export const CHANGEUSERPROFILE = 'CHANGEUSERPROFILE';
export const ADDSKILLREDUX = 'ADDSKILLREDUX';
export const ADDEXPREDUX = 'ADDEXPREDUX';
export const REMOVESKILLREDUX = 'REMOVESKILLREDUX';
export const REMOVEEXPREDUX = 'REMOVEEXPREDUX';
